# Generated by Django 2.1.5 on 2019-03-04 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slide_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('author_username', models.CharField(max_length=10)),
                ('author_forename', models.CharField(max_length=30)),
                ('author_surname', models.CharField(max_length=30)),
                ('session_code', models.CharField(max_length=6, unique=True)),
                ('is_running', models.BooleanField()),
                ('is_taking_questions', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Lecture')),
            ],
        ),
    ]
