# Generated by Django 2.1.5 on 2019-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
    ]
