# Generated by Django 2.1.5 on 2019-03-05 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20190305_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('time_posted', models.DateTimeField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Session')),
            ],
        ),
    ]
