# Generated by Django 2.1.5 on 2019-03-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
