# Generated by Django 2.1.5 on 2019-03-10 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20190305_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='session_code',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters allowed.')]),
        ),
    ]
