# Generated by Django 2.1.5 on 2019-03-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20190310_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField()),
                ('overall_feedback', models.CharField(choices=[('POSITIVE', 'Good'), ('NEGATIVE', 'Bad'), ('NEUTRAL', 'So-So')], default='', max_length=30)),
                ('delivery_speed', models.CharField(choices=[('V-SLOW', 'Very Slow'), ('SLOW', 'Little Slow'), ('NORMAL', 'Just Right'), ('FAST', 'Little Fast'), ('V-FAST', 'Very Fast')], default='NORMAL', max_length=30)),
                ('content_complexity', models.CharField(choices=[('V-HARD', 'Very Difficult'), ('HARD', 'Slightly Difficult'), ('NORMAL', 'Normal'), ('EASY', 'Slightly Easy'), ('V-EASY', 'Very Easy')], default='', max_length=30)),
                ('content_presentation', models.CharField(choices=[('NEGATIVE', 'Not Well Presented'), ('NEUTRAL', 'Well Presented'), ('POSITIVE', 'Very Well Presented')], default='', max_length=30)),
                ('level_of_engagement', models.CharField(choices=[('NEGATIVE', 'Not Engaging/Interesting'), ('NEUTRAL', 'Engaging/Interesting'), ('POSITIVE', 'Very Engaging/Interesting')], default='', max_length=30)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Session')),
            ],
        ),
    ]
