# Generated by Django 2.1.5 on 2019-03-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='lecture_id',
            new_name='lecture',
        ),
    ]
