# Generated by Django 2.1.5 on 2019-03-11 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20190310_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 11, 44, 57, 61875, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
