# Generated by Django 2.1.5 on 2019-03-14 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_lecture_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='slide_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
