# Generated by Django 2.1.5 on 2019-03-31 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190315_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartEndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content_complexity',
            field=models.CharField(choices=[('V-EASY', 'Very Easy'), ('EASY', 'Slightly Easy'), ('NORMAL', 'Normal'), ('HARD', 'Slightly Difficult'), ('V-HARD', 'Very Difficult')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content_presentation',
            field=models.CharField(choices=[('POSITIVE', 'Very Well Presented'), ('NEUTRAL', 'Well Presented'), ('NEGATIVE', 'Not Well Presented')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='level_of_engagement',
            field=models.CharField(choices=[('POSITIVE', 'Very Engaging/Interesting'), ('NEUTRAL', 'Engaging/Interesting'), ('NEGATIVE', 'Not Engaging/Interesting')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_feedback',
            field=models.CharField(choices=[('POSITIVE', 'Good'), ('NEUTRAL', 'So-So'), ('NEGATIVE', 'Bad')], default='', max_length=30),
        ),
    ]
