# Generated by Django 2.1.5 on 2019-04-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20190331_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
    ]
