# Generated by Django 2.1.5 on 2019-04-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20190401_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startendtime',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='staff.Session'),
        ),
    ]
