# Generated by Django 2.1.5 on 2019-04-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20190401_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startendtime',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Session'),
        ),
    ]
