# Generated by Django 2.1.5 on 2019-04-01 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20190401_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startendtime',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('start_time',)},
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 20, 45, 38, 507540, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='total_runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StartEndTime',
        ),
    ]
