# Generated by Django 2.1.5 on 2019-04-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20190401_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.DateTimeField()),
            ],
            options={
                'ordering': ('end',),
            },
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_runtime',
        ),
        migrations.AddField(
            model_name='starttime',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Session'),
        ),
        migrations.AddField(
            model_name='endtime',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Session'),
        ),
    ]
