# Generated by Django 2.1.5 on 2019-04-08 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20190402_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content_complexity',
            field=models.CharField(blank=True, choices=[(None, 'Not Specified'), ('V-EASY', 'Very Easy'), ('EASY', 'Slightly Easy'), ('NORMAL', 'Normal'), ('HARD', 'Slightly Difficult'), ('V-HARD', 'Very Difficult')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content_presentation',
            field=models.CharField(blank=True, choices=[(None, 'Not Specified'), ('POSITIVE', 'Very Well Presented'), ('NEUTRAL', 'Well Presented'), ('NEGATIVE', 'Not Well Presented')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='delivery_speed',
            field=models.CharField(blank=True, choices=[(None, 'Not Specified'), ('V-SLOW', 'Very Slow'), ('SLOW', 'Little Slow'), ('NORMAL', 'Just Right'), ('FAST', 'Little Fast'), ('V-FAST', 'Very Fast')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='level_of_engagement',
            field=models.CharField(blank=True, choices=[(None, 'Not Specified'), ('POSITIVE', 'Very Engaging/Interesting'), ('NEUTRAL', 'Engaging/Interesting'), ('NEGATIVE', 'Not Engaging/Interesting')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_feedback',
            field=models.CharField(blank=True, choices=[(None, 'Not Specified'), ('POSITIVE', 'Good'), ('NEUTRAL', 'So-So'), ('NEGATIVE', 'Bad')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='slide_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
