# Generated by Django 2.1.5 on 2019-04-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20190408_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
