# Generated by Django 2.1.5 on 2019-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_lecture_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('time__start',)},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
