# Generated by Django 2.1.5 on 2019-02-05 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slide_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
